"""added IndexAsset ass table and removed many-to-many Asset to User


Revision ID: 0710ada769f6
Revises: 769fffd070a5
Create Date: 2020-03-22 00:50:39.505420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0710ada769f6'
down_revision = '769fffd070a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('allocation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('baskets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('index_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('percent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], name='baskets_asset_id_fkey'),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], name='baskets_index_id_fkey')
    )
    op.drop_table('index_asset')
    # ### end Alembic commands ###
