"""IndexAsset.asset_id into asset from int to str in form

Revision ID: 09609e9c352b
Revises: bc8215a90df8
Create Date: 2020-03-25 15:30:05.327578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09609e9c352b'
down_revision = 'bc8215a90df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('index_asset_asset_id_fkey', 'index_asset', type_='foreignkey')
    op.drop_column('index_asset', 'asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('index_asset_asset_id_fkey', 'index_asset', 'asset', ['asset_id'], ['id_cmc'])
    # ### end Alembic commands ###
