"""added Index.name

Revision ID: 0a5fd53ec84c
Revises: 3cd5f87ff122
Create Date: 2020-03-20 20:58:29.255996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5fd53ec84c'
down_revision = '3cd5f87ff122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index', 'name')
    # ### end Alembic commands ###
