"""remove unique to Quote.slug

Revision ID: 3cd5f87ff122
Revises: ac4d8bb27702
Create Date: 2020-03-20 02:06:44.441333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd5f87ff122'
down_revision = 'ac4d8bb27702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quote_slug', table_name='quote')
    op.create_index(op.f('ix_quote_slug'), 'quote', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_slug'), table_name='quote')
    op.create_index('ix_quote_slug', 'quote', ['slug'], unique=True)
    # ### end Alembic commands ###
