"""IndexAsset.asset_id FK from asset.id to asset.ic_cmc

Revision ID: 3ddd567d50b9
Revises: d93733266652
Create Date: 2020-03-25 16:15:35.749064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ddd567d50b9'
down_revision = 'd93733266652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('index_asset_asset_id_fkey', 'index_asset', type_='foreignkey')
    op.create_foreign_key(None, 'index_asset', 'asset', ['asset_id'], ['id_cmc'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'index_asset', type_='foreignkey')
    op.create_foreign_key('index_asset_asset_id_fkey', 'index_asset', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###
