"""Asset.rank uniquer again ahah

Revision ID: 4fb8ec0ae66b
Revises: 640f51f373cb
Create Date: 2020-03-20 01:52:54.103135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb8ec0ae66b'
down_revision = '640f51f373cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'asset', ['rank'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset', type_='unique')
    # ### end Alembic commands ###
