"""changed IndeaxAsset.asset foreignkey into assetname bc duplicate with db.relationship

Revision ID: 59ba847d183a
Revises: 806f93cf1b07
Create Date: 2020-03-25 15:34:35.156273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ba847d183a'
down_revision = '806f93cf1b07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('assetname', sa.String(length=120), nullable=True))
    op.drop_constraint('index_asset_asset_id_fkey', 'index_asset', type_='foreignkey')
    op.create_foreign_key(None, 'index_asset', 'asset', ['assetname'], ['assetname'])
    op.drop_column('index_asset', 'asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'index_asset', type_='foreignkey')
    op.create_foreign_key('index_asset_asset_id_fkey', 'index_asset', 'asset', ['asset_id'], ['id_cmc'])
    op.drop_column('index_asset', 'assetname')
    # ### end Alembic commands ###
