"""Index.asset_id from integer to array of integer

Revision ID: 5fe801820a98
Revises: 0a5fd53ec84c
Create Date: 2020-03-21 14:59:28.215552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fe801820a98'
down_revision = '0a5fd53ec84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('index_asset_id_fkey', 'index', type_='foreignkey')
    op.drop_column('index', 'asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('index_asset_id_fkey', 'index', 'asset', ['asset_id'], ['id'])
    # ### end Alembic commands ###
