"""Asset.rank not uniquer anymore

Revision ID: 640f51f373cb
Revises: f2cb84d61325
Create Date: 2020-03-20 01:44:54.118402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640f51f373cb'
down_revision = 'f2cb84d61325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_rank_key', 'asset', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('asset_rank_key', 'asset', ['rank'])
    # ### end Alembic commands ###
