"""Quote.last_updated_usd into Quote.last_updated

Revision ID: 6982b700c427
Revises: faf7bbf418a6
Create Date: 2020-03-24 14:14:42.966507

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6982b700c427'
down_revision = 'faf7bbf418a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.drop_column('quote', 'last_updated_usd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('last_updated_usd', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('quote', 'last_updated')
    # ### end Alembic commands ###
