"""removed user/asset relationship, created many-to-many index/asset

Revision ID: 769fffd070a5
Revises: 96a875d6f0d4
Create Date: 2020-03-21 18:29:08.623961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769fffd070a5'
down_revision = '96a875d6f0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('index_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('percent', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['index.id'], )
    )
    op.drop_constraint('index_user_id_fkey', 'index', type_='foreignkey')
    op.drop_column('index', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('index_user_id_fkey', 'index', 'user', ['user_id'], ['id'])
    op.drop_table('baskets')
    # ### end Alembic commands ###
