"""changed IndeaxAsset.asset foreignkey into assetname bc duplicate with db.relationship

Revision ID: 806f93cf1b07
Revises: 09609e9c352b
Create Date: 2020-03-25 15:32:56.795023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806f93cf1b07'
down_revision = '09609e9c352b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('assetname', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'index_asset', 'asset', ['assetname'], ['assetname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'index_asset', type_='foreignkey')
    op.drop_column('index_asset', 'assetname')
    # ### end Alembic commands ###
