"""index.asset_id from int to array of integer

Revision ID: 85025d9c171e
Revises: 5fe801820a98
Create Date: 2020-03-21 15:03:51.926799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85025d9c171e'
down_revision = '5fe801820a98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index', 'name')
    # ### end Alembic commands ###
