"""One user has many index:


Revision ID: 90744ecb2606
Revises: 0710ada769f6
Create Date: 2020-03-22 01:32:16.844489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90744ecb2606'
down_revision = '0710ada769f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'index', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'index', type_='foreignkey')
    op.drop_column('index', 'user_id')
    # ### end Alembic commands ###
