"""pickle for Asset.platform

Revision ID: ac4d8bb27702
Revises: c1c3a34acdb4
Create Date: 2020-03-20 02:00:50.240803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4d8bb27702'
down_revision = 'c1c3a34acdb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('platform', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'platform')
    # ### end Alembic commands ###
