"""remove Asset.platform

Revision ID: c1c3a34acdb4
Revises: 4fb8ec0ae66b
Create Date: 2020-03-20 02:00:20.818295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c3a34acdb4'
down_revision = '4fb8ec0ae66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset', 'platform')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('platform', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
