"""IndexAsset.assetname into asset_id

Revision ID: d93733266652
Revises: 59ba847d183a
Create Date: 2020-03-25 16:12:26.328640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93733266652'
down_revision = '59ba847d183a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_constraint('index_asset_assetname_fkey', 'index_asset', type_='foreignkey')
    op.create_foreign_key(None, 'index_asset', 'asset', ['asset_id'], ['id'])
    op.drop_column('index_asset', 'assetname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index_asset', sa.Column('assetname', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'index_asset', type_='foreignkey')
    op.create_foreign_key('index_asset_assetname_fkey', 'index_asset', 'asset', ['assetname'], ['assetname'])
    op.drop_column('index_asset', 'asset_id')
    # ### end Alembic commands ###
