"""added Index.amount and Index.currency

Revision ID: faf7bbf418a6
Revises: 90744ecb2606
Create Date: 2020-03-22 22:07:17.991383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf7bbf418a6'
down_revision = '90744ecb2606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('index', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('index', sa.Column('currency', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index', 'currency')
    op.drop_column('index', 'amount')
    # ### end Alembic commands ###
